"""empty message

Revision ID: 72eb476c678f
Revises: 5dc067c75f80
Create Date: 2025-11-22 13:01:24.160036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72eb476c678f'
down_revision: Union[str, None] = '5dc067c75f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vk_messages',
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('peer_id', sa.Integer(), nullable=False),
    sa.Column('from_chat', sa.Boolean(), nullable=False),
    sa.Column('from_bot', sa.Boolean(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('reply_message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('en', sa.Boolean(), nullable=False),
    sa.Column('ctime', sa.TIMESTAMP(), server_default=sa.text("(NOW() at time zone 'utc')"), nullable=False),
    sa.Column('atime', sa.TIMESTAMP(), nullable=True),
    sa.Column('dtime', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_messages_from_bot'), 'vk_messages', ['from_bot'], unique=False)
    op.create_index(op.f('ix_vk_messages_from_id'), 'vk_messages', ['from_id'], unique=False)
    op.create_index(op.f('ix_vk_messages_peer_id'), 'vk_messages', ['peer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vk_messages_peer_id'), table_name='vk_messages')
    op.drop_index(op.f('ix_vk_messages_from_id'), table_name='vk_messages')
    op.drop_index(op.f('ix_vk_messages_from_bot'), table_name='vk_messages')
    op.drop_table('vk_messages')
    # ### end Alembic commands ###
